### ISSUE TITLE
[Request] Neoforge 1.21 port?

### ISSUE THREAD

**Issue by K1ritoz** [Thadah/hibernateforge#2]
Hey! Any plans to port this mod to NeoForge 1.21.1? It would be awesome to have support for that version.

**Comment by Thadah** [comment]
I published a new version for Neoforge with MC 1.21.6, let me know if it works properly!

**Comment by K1ritoz** [comment]
Thanks a lot, you’re awesome! Unfortunately, it didn’t work on 1.21.1 (which is the version used by ATM10). Do you think adjusting the version range in mods.toml could make it compatible?

**Comment by Thadah** [comment]
I'll try to publish the mod for that version, maybe it's just about lowering the version range

**Comment by Thadah** [comment]
Test this version https://modrinth.com/mod/hibernateforge/version/efmxWxgY and let me know if it works for 1.21.1

**Comment by K1ritoz** [comment]
Tried it, but sadly it still doesn’t work on 1.21.1. Added some screenshots for reference

![Image](https://github.com/user-attachments/assets/c29ae8e8-b4e7-4ce6-a0dd-6cb6d7c3f9a5)
![Image](https://github.com/user-attachments/assets/eb4b9948-bb06-4b04-b155-092bf5bd2330)

**Comment by Thadah** [comment]
Ok, I increased the version range for neoforge and established the version range from 1.21.1 to 1.22. I think it should work now.

https://modrinth.com/mod/hibernateforge/version/AXcd2lTL

**Comment by K1ritoz** [comment]
![Image](https://github.com/user-attachments/assets/a2b2ba60-6268-4e43-8d41-34e0c51c389b)
![Image](https://github.com/user-attachments/assets/ddde6bab-c71b-4865-8d00-256f3b71e35a)

**Comment by Thadah** [comment]
I made a careless mistake when setting the version ranges that made the neoforge toml invalid. I don't have a test server so I couldn't see it, sorry. This version should work, but if it doesn't I'll make one specifically for 1.21.1

https://modrinth.com/mod/hibernateforge/version/6KKzJV67

**Comment by K1ritoz** [comment]
Hey, thanks a lot! You're insane for getting this out so quickly.

I'm still getting this error when trying to load it:
`[main/ERROR] [loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies: Mod ID: 'neoforge', Requested by: 'hibernateforge', Expected range: '[21.1.194,)', Actual version: '21.1.191'
`
Would fixing this be as simple as changing the version range in `gradle.properties` and rebuilding it? I can't update the server NeoForge version right now because I’m afraid of breaking other mods.

Thanks again!

**Comment by Thadah** [comment]
That should actually be enough, yes. I'm sending another jar hoping that this time your server will accept it, I didn't know your neoforge version so I took the last stable one for 1.21.1 ^^'

https://modrinth.com/mod/hibernateforge/version/xwblbROL

**Comment by K1ritoz** [comment]
It worked perfectly on 1.21.1! Thank you so much for the quick help, you're awesome!

**Comment by Thadah** [comment]
Great! I'll commit the change then. Thank you very much for your testing!
